In [1]:
#from sklearn.feature_extraction.text import TfidfVectorizer
import pickle

tfidf_voca_agnews = pickle.load(open("tfidf_voca_agnews.pkl", "rb"))
print("vocabulary: ", len(tfidf_voca_agnews), tfidf_voca_agnews)

tfidf_arr_agnews = pickle.load(open("tfidf_arr_agnews.pkl", "rb"))
print("array: ", tfidf_arr_agnews.shape[0], tfidf_arr_agnews.shape[1], tfidf_arr_agnews)

vocabulary:  19362 {'wall': 18602, 'st': 16168, 'bear': 1978, 'claw': 3557, 'black': 2282, 'reuter': 14339, 'street': 16428, 'dwindl': 5341, 'band': 1824, 'green': 7349, 'carlyl': 3076, 'look': 10107, 'commerci': 3791, 'aerospac': 754, 'privat': 13436, 'invest': 8758, 'firm': 6359, 'group': 7417, 'ha': 7525, 'reput': 14258, 'make': 10342, 'occasion': 12047, 'controversi': 4007, 'play': 13072, 'defens': 4633, 'industri': 8530, 'quietli': 13726, 'place': 13037, 'bet': 2139, 'anoth': 1196, 'market': 10477, 'oil': 12099, 'economi': 5426, 'cloud': 3618, 'stock': 16355, 'outlook': 12359, 'soar': 15836, 'crude': 4295, 'price': 13401, 'plu': 13110, 'worri': 19080, 'earn': 5375, 'expect': 5966, 'hang': 7615, 'week': 18752, 'dure': 5316, 'depth': 4748, 'summer': 16583, 'doldrum': 5091, 'iraq': 8800, 'halt': 7573, 'export': 5993, 'main': 10324, 'southern': 15961, 'pipelin': 13001, 'author': 1630, 'flow': 6504, 'intellig': 8680, 'rebel': 13968, 'militia': 10973, 'strike': 16443, 'infrastructur': 8

array:  120000 19362 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
print(type(tfidf_voca_agnews), type(tfidf_arr_agnews))

<class 'dict'> <class 'numpy.ndarray'>


In [4]:
# 일단 다시 튜토리얼로 돌아가서 해봐 https://scikit-learn.org/stable/auto_examples/text/plot_document_clustering.html#clustering-sparse-data-with-k-means

import numpy as np
from sklearn.cluster import KMeans

# kmeans = [0,0,0,0,0,0,0]
for seed in range(1,3):
    kmeans[seed] = KMeans(
        n_clusters=4,  # AGNEWS가 4개니깐!
        max_iter=100,
        n_init=5,
        random_state=seed,
    ).fit(tfidf_arr_agnews)
    cluster_idf, cluster_sizes = np.unique(kmeans[seed].labels_, return_counts=True)
    print(f"# of elements asigned to each cluster: {cluster_sizes}")

# of elements asigned to each cluster: [ 7769 13833 91712  6686]
# of elements asigned to each cluster: [ 7718  6737 96670  8875]


In [5]:
print(kmeans)

[0, KMeans(max_iter=100, n_clusters=4, n_init=5, random_state=1), KMeans(max_iter=100, n_clusters=4, n_init=5, random_state=2), 0, 0, 0, 0]


In [5]:
print(kmeans[4].labels_)

cluster_idf, cluster_sizes = np.unique(kmeans[4].labels_, return_counts=True)
print(cluster_idf, cluster_sizes)

[2 2 0 ... 3 3 3]
[0 1 2 3] [ 3436  7834 16726 92004]


In [7]:
original_space_centroids = kmeans[4].cluster_centers_
order_centroids = original_space_centroids.argsort()[:, ::-1]
terms = tfidf_voca_agnews

for i in range(4):
    print(f"Cluster {i}: ", end="")
    for ind in order_centroids[i, :10]:
        word = [key for key, value in terms.items() if value == ind]
        print(f"{word[0]} ", end="")
    print()

Cluster 0: oil price stock crude barrel reuter high suppli higher record 
Cluster 1: ap u hi bush said wa game new presid state 
Cluster 2: reuter &lt kill iraq u said /b&gt b&gt iraqi baghdad 
Cluster 3: new ha quot hi wa said year compani world game 


In [9]:
for i in range(4):
    print(f"Cluster {i}: ", end="")
    for ind in order_centroids[i, :10]:
        print(f"{ind} ", end="")
    print()

Cluster 0: 12099 13401 16355 4295 1886 14339 7918 16637 7945 14018 
Cluster 1: 1288 17837 7903 2861 14759 18563 6931 11668 13375 16251 
Cluster 2: 14339 45 9396 8800 17837 14759 99 1713 8801 1765 
Cluster 3: 11668 7525 13738 7903 18563 14759 19218 3811 19070 6931 


In [6]:
# pickle로 kmeans 모델 백업

pickle.dump(kmeans, open("kmeans_agnews_all.pkl", "wb"))

In [10]:
# 로드 테스트

kmeans_agnews_all = pickle.load(open("kmeans_agnews_all.pkl", "rb"))
print(kmeans_agnews_all)
#print("labels: ", len(kmeans_agnews_all[3].labels_), kmeans_agnews_all[3].labels_)



[0, KMeans(max_iter=100, n_clusters=4, n_init=5, random_state=1), KMeans(max_iter=100, n_clusters=4, n_init=5, random_state=2), 0, 0, 0, 0]


In [14]:
len(kmeans_agnews_all[3].labels_)

AttributeError: 'int' object has no attribute 'labels_'